bookshelf_st/config/routes.rb
Rails.application.routes.draw do
  resources :books
  root 'welcome#welcome'
  resources :authors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

bookshelf_st/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookshelf_st/app/models/author.rb
class Author < ApplicationRecord
  
  has_many :books, dependent: :destroy
  accepts_nested_attributes_for :books, allow_destroy: true
  
  scope :get_by_name, ->(name) {
    where("name like ?", "%#{name}%")
  }

end

bookshelf_st/app/models/author_form.rb
class AuthorForm
  include Virtus

  extend ActiveModel::Naming
  include ActiveModel::Conversion
  include ActiveModel::Validations

  attribute :name, String

  # validationが必要ならここにvalidatesを書ける
  #  validates :name, presence: true

  def search
    #@authors = Author.where("name LIKE ?", "%#{params[:name]}%")
    scoped = Author.scoped
    scoped = Author.where("name LIKE ?", "%#{name}%") if name.present?
    scoped
  end
end

bookshelf_st/app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :author
  

  validates :title, presence: true

end

bookshelf_st/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

bookshelf_st/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
    if params[:name].present?
      @authors = @authors.get_by_name params[:name]
    end
    #@author_form = AuthorForm.new params[:author_form]
    #@authors = @author_form.search
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
    @author.books.build
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name, books_attributes: [:id, :title, :is_leded])
    end
end

bookshelf_st/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author_id)
    end
end

bookshelf_st/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def welcome
  end
end

bookshelf_st/app/helpers/application_helper.rb
module ApplicationHelper
end

bookshelf_st/app/helpers/authors_helper.rb
module AuthorsHelper
end

bookshelf_st/app/helpers/books_helper.rb
module BooksHelper
end

bookshelf_st/app/helpers/welcome_helper.rb
module WelcomeHelper
end

bookshelf_st/app/views/authors/_form.html.erb
<%= form_for(author) do |f| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :名前 %>
    <%= f.text_field :name %>
    <%= f.label :年齢 %>
    <%= f.text_field :age %>
  </div>

  <!-- <div class="field">
    <%= f.label :books, "著書" %><br />
    <%= f.fields_for :books do |books_form| %>
      <%= books_form.label :title, "タイトル" %>
      <%= books_form.text_field :title %><br />
      <%= books_form.label :is_lended, "レンタル中" %>
      <%= books_form.text_field :is_lended %><br />
    <% end %>
  </div> -->

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

bookshelf_st/app/views/authors/edit.html.erb
<h1>作者編集</h1>

<%= render 'form', author: @author %>

<%= link_to '詳細', @author %> |
<%= link_to '戻る', authors_path %>

bookshelf_st/app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>作者</h1>

<div>
  <%= form_tag(authors_path, method: "get") do %>
    <%= text_field_tag :name, params[:name] %>
    <%= submit_tag "検索" %>
  <% end %>
</div>
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>名前</th>
      <th>年齢</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.id %></td>
        <td><%= author.name %></td>
        <td><%= author.age %></td>
        <td><%= link_to '詳細', author %></td>
        <td><%= link_to '編集', edit_author_path(author) %></td>
        <td><%= link_to '削除', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <!-- <% author.books.each do |book| %>
         <tr>
           <td><%= book.title %></td>
           <td><%= book.author_id %></td>
           <td><%= link_to '詳細', book %></td>
           <td><%= link_to '編集', edit_book_path(book) %></td>
           <td><%= link_to '削除', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
         </tr>
       <% end %> -->
    <% end %>
  </tbody>
</table>

<br>

<div class="buttondiv">
  <%= link_to '新規登録', new_author_path, { :class => "linkbutton" } %>
</div>

bookshelf_st/app/views/authors/new.html.erb
<h1>作者新規登録</h1>

<%= render 'form', author: @author %>

<%= link_to 'Back', authors_path %>

bookshelf_st/app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

bookshelf_st/app/views/books/_form.html.erb
<%= form_for(book) do |f| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :タイトル %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :作者 %>
    <%= f.collection_select :author_id, Author.all, :id, :name %>
  </div>

  <div class="field">
    <%= f.label :レンタル中 %>
    <%= f.check_box 'is_lended', {}, true, false %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

bookshelf_st/app/views/books/edit.html.erb
<h1>書籍編集</h1>

<%= render 'form', book: @book %>

<%= link_to '詳細', @book %> |
<%= link_to '戻る', books_path %>

bookshelf_st/app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>タイトル</th>
      <th>貸出中</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.is_lended %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

bookshelf_st/app/views/books/new.html.erb
<h1>書籍新規登録</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

bookshelf_st/app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author_id %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

bookshelf_st/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookshelfSt</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

bookshelf_st/app/views/welcome/welcome.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>トップ</title>
</head>
<body>
  <div class="buttondiv">  
    <a href="/authors" class="linkbutton">作者一覧</a>
  </div>
</body>
</html>